name = "Taped"
uuid = "07d77754-e150-4737-8c94-cd238a1fb45b"
authors = ["Will Tebbutt and contributors"]
version = "1.0.0-DEV"

[deps]
DiffRules = "b552c78f-8df3-52c6-915a-8e097449b14b"
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Umlaut = "92992a2b-8ce5-4a9c-bb9d-58be9a7dc841"

[compat]
BenchmarkTools = "1"
DiffRules = "1"
ExprTools = "0.1"
FunctionWrappers = "1"
JET = "0.8"
Setfield = "1"
Umlaut = "0.5"
julia = "1"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BenchmarkTools", "Test"]
